# Generated by Django 2.0 on 2018-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171217_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced_profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
