# Generated by Django 2.0 on 2018-03-04 15:21

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_advanced_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced_profile',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
