# Generated by Django 2.0 on 2018-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_advanced_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced_profile',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advanced_profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Άνδρας'), ('FEMALE', 'Γυναίκα')], default='MALE', max_length=6),
        ),
    ]
