# Generated by Django 2.0 on 2018-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20171227_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
