# Generated by Django 2.0 on 2018-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/event_video_uploads/%D/%M/%Y'),
        ),
    ]
