# Generated by Django 2.0 on 2018-05-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0018_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='Events.Event'),
        ),
    ]
